name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install headless run dependencies
        run: sudo apt-get install -y xvfb 

      - name: Install dependencies
        run: npm install

      - name: Eslint
        run: npm run eslint

      - name: Tests
        run: |
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          npm run test
      
      - name: Build
        run: npm run build
